apiVersion: v1
kind: Service
metadata:
  name: myweb
  annotations:
    service.beta.kubernetes.io/qingcloud-load-balancer-eip-ids: "eip-uf3zqgmx"
    service.beta.kubernetes.io/qingcloud-load-balancer-type: "0"
spec:
  ports:
  - name: myweb-svc
    port: 8080
    targetPort: 8080
    nodePort: 32767
  selector:
    app: myweb
  type: LoadBalancer
  externalIPs: 
  - 139.198.191.159
